name: Compile and test

on:
  push:
    branches:
      - main
      - developer
    # paths:
      # - 'src/**'
  pull_request:
    branches:
      - main
      - developer
    # paths:
      # - 'src/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build/*
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ../bin/test
